apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: tomasandel123/ambulance-ufe
  newName: tomasandel123/ambulance-ufe
  newTag: 1.1.0

- name: tomasandel123/andel-project-webapi
  newName: tomasandel123/andel-project-webapi
  newTag: 1.1.0