apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital  
                         
labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/andel-project-ufe
- ../../../apps/andel-project-webapi

patches:
- path: patches/ambulance-webapi.service.yaml

components:
- ../../../components/version-developers
- https://github.com/tomasandel/andel-project-webapi///deployments/kustomize/components/mongodb