apiVersion: apps/v1
kind: Deployment
metadata:
  name: andel-project-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /andel-project-openapi
            - name: BASE_URL
              value: /andel-project-openapi-ui