kind: Service
apiVersion: v1
metadata:
  name: andel-project-openapi-ui
spec:
  selector:
    pod: andel-project-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081