apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: andel-project-ufe-content
spec:
  microFrontend: andel-project-ufe
  element: andel-project-q-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?andel-project-q(/.*)?$"